
[project]
name = "robust-kernels-for-robust-location-estimation"
version = "0.1.0"
description = "Robust kernels for robust location estimation"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"

dependencies = [
    "numpy",
    "scikit-learn",
]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]